### ISSUE TITLE
MacOSX deprecated warning

### ISSUE THREAD

**Issue by beihaifeiwu** [browserutils/kooky#60]
# github.com/keybase/go-keychain
cgo-gcc-prolog:53:11: warning: 'SecKeychainItemDelete' is deprecated: first deprecated in macOS 10.10 - SecKeychain is deprecated [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychainItem.h:257:10: note: 'SecKeychainItemDelete' has been explicitly marked deprecated here

**Comment by srlehn** [comment]
This is https://github.com/keybase/go-keychain/issues/97 fixed in https://github.com/keybase/go-keychain/pull/99 - we need to update that dependency.

---

keybase/go-keychain is used for the cgo darwin implementation for chrome in [chrome_darwin_cgo.go](https://github.com/browserutils/kooky/blob/4c50211/internal/chrome/chrome_darwin_cgo.go#L10) - a fallback will be used when compiled with CGO_ENABLED=0 (executing macOS own "security" tool instead).

**Comment by srlehn** [comment]
fixed by 4c50211
